"""empty message

Revision ID: 0322a6ec3fcc
Revises: d959fe6614c3
Create Date: 2024-06-10 22:03:46.416298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0322a6ec3fcc'
down_revision = 'd959fe6614c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_puzzle_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_puzzle_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_puzzle_category_id'))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
