"""fix Message model add column issue

Revision ID: 2a6c86ef5c30
Revises: 3b1e7290c131
Create Date: 2024-06-24 14:32:07.977086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6c86ef5c30'
down_revision = '3b1e7290c131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_deleted_by_sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted_by_sender', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
