"""Allow puzzle_id to be NULL in Message model

Revision ID: 3724f113e60f
Revises: d310568f8db6
Create Date: 2024-06-19 21:00:29.438681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '3724f113e60f'
down_revision = 'd310568f8db6'
branch_labels = None
depends_on = None

# get actual constraint name
def get_constraint_name():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    constraints = inspector.get_foreign_keys('message')
    for constraint in constraints:
        if constraint['referred_table'] == 'puzzle':
            return constraint['name']
    return None

# drop table if exists
def drop_temp_table_if_exists(table_name):
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if table_name in inspector.get_table_names():
        op.execute(f"DROP TABLE {table_name}")

def upgrade():
    # Get the actual foreign key constraint name
    constraint_name = get_constraint_name()
    # drop temp table if it exists- fix issue with temp table for message already exsiting from previous error
    drop_temp_table_if_exists('_alembic_tmp_message')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:   
        batch_op.alter_column('puzzle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # drop constraint it it exists
        if constraint_name:
            batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.create_foreign_key('fk_message_puzzle_id', 'puzzle', ['puzzle_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    constraint_name = 'fk_message_puzzle_id'
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.create_foreign_key('fk_message_puzzle_id', 'puzzle', ['puzzle_id'], ['id'])
        batch_op.alter_column('puzzle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
