"""add is_deleted_by_recipient to Message model

Revision ID: 3b1e7290c131
Revises: 7f659a867c4e
Create Date: 2024-06-24 13:42:36.655500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1e7290c131'
down_revision = '7f659a867c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_deleted_by_recipient')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted_by_recipient', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###
