"""add is_deleted to Message model

Revision ID: 50dd730182d7
Revises: 8d6ded3d5784
Create Date: 2024-06-21 21:04:19.141329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dd730182d7'
down_revision = '8d6ded3d5784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_puzzle')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    op.create_table('_alembic_tmp_puzzle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pieces', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('is_requested', sa.BOOLEAN(), nullable=False),
    sa.Column('in_progress', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
