"""change is_deleted to specific sender or recipient in messages model

Revision ID: 7f659a867c4e
Revises: 50dd730182d7
Create Date: 2024-06-24 12:19:29.242573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '7f659a867c4e'
down_revision = '50dd730182d7'
branch_labels = None
depends_on = None

# drop table if exists
def drop_temp_table_if_exists(table_name):
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if table_name in inspector.get_table_names():
        op.execute(f"DROP TABLE {table_name}")
def upgrade():
    drop_temp_table_if_exists('_alembic_tmp_message')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted_by_sender', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_deleted_by_sender')

    # ### end Alembic commands ###
