"""to return puzzle_id to not null in Message

Revision ID: 8d6ded3d5784
Revises: 3724f113e60f
Create Date: 2024-06-21 19:12:15.769465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '8d6ded3d5784'
down_revision = '3724f113e60f'
branch_labels = None
depends_on = None

# get actual constraint name
def get_constraint_name():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    constraints = inspector.get_foreign_keys('message')
    for constraint in constraints:
        if constraint['referred_table'] == 'puzzle':
            return constraint['name']
    return None

# drop table if exists
def drop_temp_table_if_exists(table_name):
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if table_name in inspector.get_table_names():
        op.execute(f"DROP TABLE {table_name}")


def upgrade():
     # Get the actual foreign key constraint name
    constraint_name = get_constraint_name()
    # drop temp table if it exists- fix issue with temp table for message already exsiting from previous error
    drop_temp_table_if_exists('_alembic_tmp_message')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_puzzle')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('puzzle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_message_puzzle_id', type_='foreignkey')
        batch_op.create_foreign_key(constraint_name, 'puzzle', ['puzzle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # Get the actual foreign key constraint name
    constraint_name = get_constraint_name()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.create_foreign_key('fk_message_puzzle_id', 'puzzle', ['puzzle_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('puzzle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_puzzle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pieces', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('is_requested', sa.BOOLEAN(), nullable=False),
    sa.Column('in_progress', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
