"""puzzles table

Revision ID: ac94c26522a6
Revises: 101b71137731
Create Date: 2024-06-04 14:11:05.058269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac94c26522a6'
down_revision = '101b71137731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_requested', sa.Boolean(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_user_id'))
        batch_op.drop_index(batch_op.f('ix_puzzle_timestamp'))

    op.drop_table('puzzle')
    # ### end Alembic commands ###
