"""add image puzzle table

Revision ID: bbf6141a4e16
Revises: 0322a6ec3fcc
Create Date: 2024-06-11 15:24:48.990252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf6141a4e16'
down_revision = '0322a6ec3fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check for and drop existing temporary table
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_category")

    # with op.batch_alter_table('category', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_category_name', ['name'])

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_index('ix_puzzle_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.create_index('ix_puzzle_category_id', ['category_id'], unique=False)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name', type_='unique')

    # ### end Alembic commands ###
