"""add condition to puzzle table

Revision ID: c428b2ba18b3
Revises: bbf6141a4e16
Create Date: 2024-06-13 14:33:23.013723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c428b2ba18b3'
down_revision = 'bbf6141a4e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        # Check for and drop existing temporary table
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_puzzle")
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=64), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
