"""change puzzle/category to m-m rltnshp

Revision ID: c45af79d075b
Revises: c428b2ba18b3
Create Date: 2024-06-13 21:19:02.378629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45af79d075b'
down_revision = 'c428b2ba18b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS puzzle_category")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_puzzle")
    op.create_table('puzzle_category',
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.PrimaryKeyConstraint('puzzle_id', 'category_id')
    )
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_constraint('fk_puzzle_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_puzzle_category_id', 'category', ['category_id'], ['id'])
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.drop_table('puzzle_category')
    # ### end Alembic commands ###
