"""mesage model

Revision ID: d310568f8db6
Revises: c45af79d075b
Create Date: 2024-06-18 13:45:32.861842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd310568f8db6'
down_revision = 'c45af79d075b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS message")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_puzzle")
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('sender_requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_owner_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.ForeignKeyConstraint(['recipient_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_puzzle_id'), ['puzzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipient_owner_id'), ['recipient_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_requester_id'), ['sender_requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_message_sender_requester_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_owner_id'))
        batch_op.drop_index(batch_op.f('ix_message_puzzle_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
